kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: thanakorn
data:
  default.conf: |
    server {
      listen 80;
      server_name_;

      location / {
        default_type application/json;
        return 200 "Hello Yiem";
      }
    }
